### ISSUE TITLE
key errors for lipidnames in local version

### ISSUE THREAD

**Issue by s-schaef** [ProLint/prolintpy#4]
Hello,

I have been trying to use prolintpy locally in jupyter to look at an atomistic system with a rather complex membrane. If I just follow the tutorial on the contact analysis (except for changing the resolution to 'atomistic') it prints out all the correct lipidnames with lipids.lipid_names()
> array(['CHL1', 'PDOPE', 'PAPS', 'PLPC', 'PLA20', 'POPI2', 'POPE', 'SAPS',
       'SAPE', 'DPPC', 'POPC', 'PSM'], dtype=object)

However, when I try to use those same lipids it returns key errors (see screenshot). This is true for most lipids I tested, except for POPC. When I submit this to the webserver it seems to work without issues. Could this be a version error? I installed prolintpy via pip install today (3rd Sep. 2021). 

Many thanks!
Stefan

![Screenshot from 2021-09-03 16-42-01_cropped](https://user-images.githubusercontent.com/89992887/132024500-941e8ac0-ba3d-4aff-8954-54ef93ba93cf.png)

**Comment by bisejdiu** [comment]
Hi Stefan, 

Try setting the `grouped` option to False, since it only works with Martini systems where the lipidome is known. 
If that does not fix the issue we can examine it further.  

Cheers

**Comment by s-schaef** [comment]
Awesome, that solved it! Thank you so much!
