### ISSUE TITLE
Using Prolint for Lipid Analysis

### ISSUE THREAD

**Issue by RayHackett** [ProLint/prolintpy#5]
I was wondering how to apply Prolint to an atomistic trajectory of a protein with a ligand.
The Tutorial indicates this is possible: https://prolint.github.io/prolintpy/#/ligands

I've tried loading my ligand (named 'LIG' in the topology) as a lipid with:
>lipids = pl.Lipids(t.topology, resolution='atomistic', lipid_names=['LIG'])

This seems to work:
>lipids.lipid_count()
{'LIG': 1}

However, running contacts.compute_neighbors gives: KeyError: 'LIG'
>contacts = pl.ComputeContacts(t, proteins, lipids)
>result = contacts.compute_neighbors(t, cutoff=0.5)

The full error message is attached.

What is the correct/intented way to load a ligand with Prolint?
[lig_error.txt](https://github.com/ProLint/prolintpy/files/8198343/lig_error.txt)

**Comment by bisejdiu** [comment]
`compute_neighbors` takes a `grouped` argument which is by default set to `True` and that will do a lipid lookup (e.g. it groups POPCs lipid into PC category). Your ligand is not recognized as part of the lipid library, hence the error. If you set `grouped=False`, it should fix this. 

Have a look at this #4

**Comment by RayHackett** [comment]
Fantastic! Thank you!
